### ISSUE TITLE
Curl finished with exit code 6

### ISSUE THREAD

**Issue by ghost** [hschneider/neutralino-curl#1]
# Describe the bug
When you click on the Download button, the file does not download and the developer console displays the error "Curl finished with exit code 6"

**Comment by hschneider** [comment]
Code 6 = Unknown host.
Did you try the latest release with this URL in main.js ?

```js
async function testCurl() {
    await CURL.download("https://marketmix.com/git-assets/neutralino-curl/test.jpg");
}
```

Some version before included a wrong URL. This is fixed in the latest release.

**Comment by ghost** [comment]
thank you, I understood the address to a different one and everything worked
I'm sorry for the trouble
